services:
  emqx:
    image: emqx:latest
    container_name: emqx
    ports:
      - "2883:1883"
      - "18083:18083"
    healthcheck:
      test: ["CMD", "emqx", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  influxdb3:
    image: influxdb:3-core
    container_name: influxdb3
    user: "0:0"
    command: ["influxdb3", "serve", "--node-id", "node0"]
    ports:
      - "8181:8181"
    volumes:
      - influxdb3_data:/root/.influxdb
    restart: always

  ingest-service:
    build:
      context: ./services/ingest_service
      dockerfile: Dockerfile
    container_name: ingest-service
    depends_on:
      emqx:
        condition: service_healthy
      influxdb3:
        condition: service_started
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always

  influxdb3-explorer:
    image: influxdata/influxdb3-ui:1.6.2
    container_name: influxdb3-explorer
    ports:
      - "8888:80"
    restart: unless-stopped
    depends_on:
      - influxdb3

  siddha-sensor-sim:
    profiles: ["replay"]
    build:
      context: ./services/siddha_sensor_sim
      dockerfile: Dockerfile
    container_name: siddha-sensor-sim
    env_file:
      - .env
    depends_on:
      emqx:
        condition: service_healthy
    volumes:
      - ./dataset:/app/dataset:ro
    restart: on-failure

  har-service:
    build:
      context: ./services/har_service
      dockerfile: Dockerfile
    container_name: har-service
    env_file:
      - .env
    depends_on:
      - influxdb3
    restart: unless-stopped

volumes:
  influxdb3_data:
