services:
  emqx:
    image: emqx:latest
    container_name: emqx
    ports:
      - "2883:1883"
      - "18083:18083"
    healthcheck:
      test: ["CMD", "emqx", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  influxdb3:
    image: influxdb:3-core
    container_name: influxdb3
    user: "0:0"
    command: ["influxdb3", "serve", "--node-id", "node0"]
    ports:
      - "8181:8181"
    volumes:
      - influxdb3_data:/root/.influxdb
    restart: always

  ingest-service:
    build:
      context: ./services/ingest_service
      dockerfile: Dockerfile
    container_name: ingest-service
    depends_on:
      emqx:
        condition: service_healthy
      influxdb3:
        condition: service_started
    env_file:
      - .env
    environment:
      MQTT_HOST: emqx
      MQTT_PORT: "1883"
      SUB_TOPICS: tennis/sensor/+/events,tennis/camera/+/ball
      INFLUX_ENABLED: "1"
    ports:
      - "8000:8000"
    restart: always


  siddha-sensor-sim:
    build:
      context: ./services/siddha_sensor_sim
      dockerfile: Dockerfile
    container_name: siddha-sensor-sim
    env_file:
      - .env
    depends_on:
      emqx:
        condition: service_healthy
    volumes:
      - ./dataset:/app/dataset:ro
    restart: on-failure

volumes:
  influxdb3_data: